### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by bimbolabuari** [alef-garrido/PortfolioAlef#10]
# Description
> This is a morning session exercise on peer-to-peer code review that demonstrates the understanding of code review as a team, code review flow, and professional code review comments.

## Suggested Changes 🙂 
-  Blank lines in HTML
-  Remove `span` as a child element of `li`
-  Use CSS styles to change elements to block instead of the `<br>` tag.
-  Avoid DRY (Don't repeat yourself). Add list-style-type property to universal tag `*`
- Use a box-sizing- border: box
-  Whitespace in the image URL link.
- Image animation moves too fast

Happy coding 🎉

**Comment by alef-garrido** [comment]
Thank you!
