### ISSUE TITLE
Peer to peer Code review exercise.

### ISSUE THREAD

**Issue by juanchernandezdev** [alef-garrido/PortfolioAlef#13]
Good job so far !!!.

You are almost there.

![](https://media3.giphy.com/media/jkSvCVEXWlOla/giphy.gif)

Maybe you can call your toggleFunction instead of the e event on your event listener for the mobile menu hamburger button and the close button.

**Comment by the-catalystmc** [comment]
My only feedback is with the toggle function as Juan said.
